/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'status' : VideoStatus,
  'duration' : bigint,
  'video' : ExternalBlob,
  'user' : Principal,
  'style' : string,
  'timestamp' : Time,
  'prompt' : string,
  'aspectRatio' : string,
}
export interface VideoGenerationJob {
  'id' : string,
  'status' : VideoStatus,
  'duration' : bigint,
  'video' : [] | [ExternalBlob],
  'user' : Principal,
  'style' : string,
  'timestamp' : Time,
  'prompt' : string,
  'aspectRatio' : string,
}
export interface VideoParams {
  'duration' : bigint,
  'style' : string,
  'prompt' : string,
  'aspectRatio' : string,
}
export type VideoStatus = { 'completed' : null } |
  { 'queued' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'finalizeJob' : ActorMethod<[string], undefined>,
  'generateVideo' : ActorMethod<[VideoParams], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[string], VideoGenerationJob>,
  'getUserJobs' : ActorMethod<[Principal], Array<VideoGenerationJob>>,
  'getUserVideos' : ActorMethod<[Principal], Array<Video>>,
  'getVideo' : ActorMethod<[string], Video>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'regenerateVideo' : ActorMethod<[string, VideoParams], string>,
  'requestAIService' : ActorMethod<[string, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateJobStatus' : ActorMethod<
    [string, VideoStatus, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];