/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoParams = IDL.Record({
  'duration' : IDL.Nat,
  'style' : IDL.Text,
  'prompt' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const VideoStatus = IDL.Variant({
  'completed' : IDL.Null,
  'queued' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const VideoGenerationJob = IDL.Record({
  'id' : IDL.Text,
  'status' : VideoStatus,
  'duration' : IDL.Nat,
  'video' : IDL.Opt(ExternalBlob),
  'user' : IDL.Principal,
  'style' : IDL.Text,
  'timestamp' : Time,
  'prompt' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'status' : VideoStatus,
  'duration' : IDL.Nat,
  'video' : ExternalBlob,
  'user' : IDL.Principal,
  'style' : IDL.Text,
  'timestamp' : Time,
  'prompt' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'finalizeJob' : IDL.Func([IDL.Text], [], []),
  'generateVideo' : IDL.Func([VideoParams], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Text], [VideoGenerationJob], ['query']),
  'getUserJobs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoGenerationJob)],
      ['query'],
    ),
  'getUserVideos' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'regenerateVideo' : IDL.Func([IDL.Text, VideoParams], [IDL.Text], []),
  'requestAIService' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateJobStatus' : IDL.Func(
      [IDL.Text, VideoStatus, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoParams = IDL.Record({
    'duration' : IDL.Nat,
    'style' : IDL.Text,
    'prompt' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const VideoStatus = IDL.Variant({
    'completed' : IDL.Null,
    'queued' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const VideoGenerationJob = IDL.Record({
    'id' : IDL.Text,
    'status' : VideoStatus,
    'duration' : IDL.Nat,
    'video' : IDL.Opt(ExternalBlob),
    'user' : IDL.Principal,
    'style' : IDL.Text,
    'timestamp' : Time,
    'prompt' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'status' : VideoStatus,
    'duration' : IDL.Nat,
    'video' : ExternalBlob,
    'user' : IDL.Principal,
    'style' : IDL.Text,
    'timestamp' : Time,
    'prompt' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'finalizeJob' : IDL.Func([IDL.Text], [], []),
    'generateVideo' : IDL.Func([VideoParams], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Text], [VideoGenerationJob], ['query']),
    'getUserJobs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoGenerationJob)],
        ['query'],
      ),
    'getUserVideos' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'regenerateVideo' : IDL.Func([IDL.Text, VideoParams], [IDL.Text], []),
    'requestAIService' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateJobStatus' : IDL.Func(
        [IDL.Text, VideoStatus, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };